# Generated by Django 3.0.4 on 2020-03-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='Aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
