# Generated by Django 3.0.4 on 2020-03-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0002_auto_20200320_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='Atracoes',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
