# Generated by Django 3.0.4 on 2020-03-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pontoturistico_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='Endereco',
            new_name='Enderecos',
        ),
    ]
