# Generated by Django 3.0.4 on 2020-03-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0005_endereco_estado'),
        ('core', '0004_auto_20200320_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='Endereco',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='enderecos.Endereco'),
        ),
    ]
