# Generated by Django 3.0.4 on 2020-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Linha1', models.CharField(max_length=150)),
                ('Linha2', models.CharField(max_length=150)),
                ('Cidade', models.CharField(max_length=150)),
                ('Pais', models.CharField(max_length=70)),
                ('Latitude', models.IntegerField()),
                ('Longitude', models.IntegerField()),
            ],
        ),
    ]
