# Generated by Django 3.0.4 on 2020-03-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Linha1', models.CharField(max_length=150)),
                ('Linha2', models.CharField(blank=True, max_length=150, null=True)),
                ('Cidade', models.CharField(max_length=150)),
                ('Estado', models.CharField(default='SP', max_length=50)),
                ('Pais', models.CharField(max_length=70)),
                ('Latitude', models.IntegerField(blank=True, null=True)),
                ('Longitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
