# Generated by Django 3.0.4 on 2020-03-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_auto_20200320_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='Latitude',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='Linha2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='Longitude',
            field=models.IntegerField(blank=True),
        ),
    ]
