# Generated by Django 3.0.4 on 2020-03-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_auto_20200320_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='Latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='Longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
