# Generated by Django 3.0.4 on 2020-03-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0005_endereco_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='Estado',
            field=models.CharField(max_length=50),
        ),
    ]
